apiVersion: v1
kind: Service
metadata:
  name: "{{ include "checkout.fullname" . }}"
  labels:
    {{- include "checkout.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "checkout.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

