apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "retail-store-ui.fullname" . }}
  labels:
    {{- include "retail-store-ui.labels" . | nindent 4 }}
data:
  APP_NAME: {{ include "retail-store-ui.name" . }}
  RELEASE: {{ include "retail-store-ui.release" . }}
  ENV: {{ .Values.env | default "production" }}

