apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catalog.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "catalog.name" . }}
data:
  {{- range .Values.config }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}

