apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "catalog.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "catalog.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "catalog.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
{{- end }}

