apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "retail-store-cart.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "retail-store-cart.name" . }}
data:
  {{- range .Values.config }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}

