{{- if .Values.app.persistence.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.persistence.secret.name }}
type: Opaque
data:
  RETAIL_ORDERS_PERSISTENCE_USERNAME: {{ .Values.app.persistence.secret.username | toString | b64enc }}
  RETAIL_ORDERS_PERSISTENCE_PASSWORD: {{ .Values.app.persistence.secret.password | toString | b64enc }}
{{- end }}

