apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retail-store-orders-ingress
  namespace: retail-store
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: retail-store.local
      http:
        paths:
          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: store-orders
                port:
                  number: 8080

