apiVersion: v1
kind: Service
metadata:
  name: {{ include "store-ui.fullname" . }}
  labels:
    {{- include "store-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort | default 0 }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}

